import { Category } from '@protowallet/types';

const generatePredefinedCategories: () => Category[] = () => [
    {
        id: 100,
        title: 'Food',
        parent: 0,
        logoId: 1,
        createdAt: new Date(),
    },
    {
        id: 101,
        title: 'Groceries',
        parent: 100,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 102,
        title: 'Restaurants',
        parent: 100,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 200,
        title: 'Entertainment',
        parent: 0,
        logoId: 2,
        createdAt: new Date(),
    },
    {
        id: 201,
        title: 'Movies',
        parent: 200,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 202,
        title: 'Games',
        parent: 200,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 300,
        title: 'Shopping',
        parent: 0,
        logoId: 3,
        createdAt: new Date(),
    },
    {
        id: 301,
        title: 'Clothing',
        parent: 300,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 302,
        title: 'Electronics',
        parent: 300,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 400,
        title: 'Transportation',
        parent: 0,
        logoId: 4,
        createdAt: new Date(),
    },
    {
        id: 401,
        title: 'Gas',
        parent: 400,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 402,
        title: 'Public Transport',
        parent: 400,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 403,
        title: 'Taxi',
        parent: 400,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 500,
        title: 'Bills',
        parent: 0,
        logoId: 5,
        createdAt: new Date(),
    },
    {
        id: 501,
        title: 'Rent',
        parent: 500,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 502,
        title: 'Utilities',
        parent: 500,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 503,
        title: 'Phone',
        parent: 500,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 600,
        title: 'Health',
        parent: 0,
        logoId: 6,
        createdAt: new Date(),
    },
    {
        id: 601,
        title: 'Doctor',
        parent: 600,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 602,
        title: 'Medicine',
        parent: 600,
        logoId: 0,
        createdAt: new Date(),
    },
    {
        id: 700,
        title: 'Other',
        parent: 0,
        logoId: 99,
        createdAt: new Date(),
    },
]

export default generatePredefinedCategories;